# Generated by Django 3.1.5 on 2021-01-24 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0002_auto_20210120_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiones',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
