# Generated by Django 3.1.5 on 2021-01-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0003_auto_20210124_1229'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Regiones',
            new_name='Regione',
        ),
    ]
