# Generated by Django 3.1.5 on 2021-01-25 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0007_auto_20210125_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regiones',
            name='id_region',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
