# Generated by Django 3.1.5 on 2021-01-26 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turismo', '0008_auto_20210125_1651'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrucel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='imagenes')),
            ],
        ),
    ]
